const config = {
  PORT: process.env.PORT || 8080,
  WEBPAGE_URL: 'http://www.mfa.gov.rs/sr/index.php/konzularni-poslovi/putovanja-u-inostranstvo/vesti-za-putovanja-u-inostranstvo/22669-----------covid-19?lang=lat',
};

export const CLOSED_BORDER = 'CLOSED_BORDER';
export const NEGATIVE_TEST_REQUIRED = 'NEGATIVE_TEST_REQUIRED';
export const NO_TEST_REQUIRED = 'NO_TEST_REQUIRED';
export const OPEN_BORDER = 'OPEN_BORDER';
export const QUARANTINE_REQUIRED = 'QUARANTINE_REQUIRED';
export const SKIP_SENTENCE = 'SKIP_SENTENCE';

export const OPEN_BORDER_INTENTS = [NEGATIVE_TEST_REQUIRED, NO_TEST_REQUIRED, QUARANTINE_REQUIRED];
export const SKIP_INTENTS = [OPEN_BORDER, SKIP_SENTENCE];

export default config;

export const RATE_LIMIT_REQUESTS = 100;
export const RATE_LIMIT_TIME = 15 * 60 * 1000; // 15 minutes

export const COUNTRY_FLAGS = {
  ALBANIJA: '🇦🇱',
  ALŽIR: '🇩🇿',
  ANDORA: '🇦🇩',
  ANGOLA: '🇦🇴',
  'ANTIGVA I BARBUDA': '🇦🇬',
  ARGENTINA: '🇦🇷',
  AUSTRALIJA: '🇦🇺',
  AUSTRIJA: '🇦🇹',
  AZERBEJDžAN: '🇦🇿',
  BAHAMI: '🇧🇸',
  BAHREIN: '🇧🇭',
  BARBADOS: '🇧🇧',
  BELGIJA: '🇧🇪',
  BELIZE: '🇧🇿',
  BELORUSIJA: '🇧🇾',
  BENIN: '🇧🇯',
  BOCVANA: '🇧🇼',
  BOLIVIJA: '🇧🇴',
  'BOSNA I HERCEGOVINA': '🇧🇦',
  BRAZIL: '🇧🇷',
  'BRUNEJI DARUSALAM': '🇧🇳',
  BUGARSKA: '🇧🇬',
  'BURKINA FASO': '🇧🇫',
  BURUNDI: '🇧🇮',
  'CENTRALNOAFRIČKA REPUBLIKA': '🇨🇫',
  'CRNA GORA': '🇲🇪',
  ČAD: '🇹🇩',
  'ČEŠKA REPUBLIKA': '🇨🇿',
  ČILE: '🇨🇱',
  DANSKA: '🇩🇰',
  'Devičanska ostrva SAD (U.S. Virgin Islands)': '🇻🇮',
  DOMINIKA: '🇩🇲',
  'DOMINIKANSKA REPUBLIKA': '🇩🇴',
  'Država Njujork': '🇺🇸',
  DžIBUTI: '🇩🇯',
  EGIPAT: '🇪🇬',
  EKVADOR: '🇪🇨',
  'EL SALVADOR': '🇸🇻',
  ERITREJA: '🇪🇷',
  ESTONIJA: '🇪🇪',
  ESVATINI: '🇸🇿',
  ETIOPIJA: '🇪🇹',
  FILIPINI: '🇵🇭',
  FINSKA: '🇫🇮',
  FIDžI: '🇫🇯',
  FRANCUSKA: '🇫🇷',
  GAMBIJA: '🇬🇲',
  GANA: '🇬🇭',
  GRČKA: '🇬🇷',
  GRENADA: '🇬🇩',
  GRUZIJA: '🇬🇪',
  GVATEMALA: '🇬🇬',
  GVAJANA: '🇬🇾',
  GVINEJA: '🇬🇳',
  'GVINEJA BISAO': '🇬🇼',
  HAITI: '🇭🇹',
  HOLANDIJA: '🇳🇱',
  'Hong Kong': '🇭🇰',
  HONDURAS: '🇭🇳',
  HRVATSKA: '🇭🇷',
  INDIJA: '🇮🇳',
  INDONEZIJA: '🇮🇩',
  IRAK: '🇮🇶',
  IRAN: '🇮🇷',
  IRSKA: '🇮🇪',
  ISLAND: '🇮🇸',
  'ISTOČNI TIMOR': '🇹🇱',
  ITALIJA: '🇮🇹',
  IZRAEL: '🇮🇱',
  JAMAJKA: '🇯🇲',
  JAPAN: '🇯🇵',
  JEMEN: '🇾🇪',
  JERMENIJA: '🇦🇲',
  JORDAN: '🇯🇴',
  'JUŽNI SUDAN': '🇸🇸',
  'JUŽNOAFRIČKA REPUBLIKA': '🇿🇦',
  'KABO VERDE': '🇨🇻',
  KAMBODžA: '🇰🇭',
  KAMERUN: '🇨🇲',
  KANADA: '🇨🇦',
  KATAR: '🇶🇦',
  KAZAHSTAN: '🇰🇿',
  KENIJA: '🇰🇪',
  KINA: '🇨🇳',
  KIPAR: '🇨🇾',
  KIRGIZIJA: '🇰🇬',
  KOLUMBIJA: '🇨🇴',
  KOMORI: '🇰🇲',
  KONGO: '🇨🇬',
  'KONGO, DR': '🇨🇩',
  'KOREJA, DNR': '🇰🇵',
  'KOREJA, Republika': '🇰🇷',
  KOSTARIKA: '🇨🇷',
  'KOT D\'IVOAR': '🇨🇮',
  KUBA: '🇨🇺',
  KUVAJT: '🇰🇼',
  LAOS: '🇱🇦',
  LESOTO: '🇱🇸',
  LETONIJA: '🇱🇻',
  LIBAN: '🇱🇧',
  LIBERIJA: '🇱🇷',
  LIBIJA: '🇱🇾',
  LIHTENŠTAJN: '🇱🇮',
  LITVANIJA: '🇱🇹',
  LUKSEMBURG: '🇱🇺',
  MADAGASKAR: '🇲🇬',
  MADjARSKA: '🇭🇺',
  Makao: '🇲🇴',
  MALAVI: '🇲🇼',
  MALDIVI: '🇲🇻',
  MALEZIJA: '🇲🇾',
  MALI: '🇲🇱',
  MALTA: '🇲🇹',
  MAROKO: '🇲🇦',
  MAURICIJUS: '🇲🇺',
  MAURITANIJA: '🇲🇷',
  MEKSIKO: '🇲🇽',
  MJANMAR: '🇲🇲',
  MOLDAVIJA: '🇲🇩',
  MONGOLIJA: '🇲🇳',
  MONAKO: '🇲🇨',
  MOZAMBIK: '🇲🇿',
  NAMIBIJA: '🇳🇦',
  NAURU: '🇳🇷',
  NEMAČKA: '🇩🇪',
  NIGER: '🇳🇪',
  NIGERIJA: '🇳🇬',
  NIKARAGVA: '🇳🇮',
  NORVEŠKA: '🇳🇴',
  'NOVI ZELAND': '🇳🇿',
  OMAN: '🇴🇲',
  PAKISTAN: '🇵🇰',
  PALAU: '🇵🇼',
  PALESTINA: '🇵🇸',
  PANAMA: '🇵🇦',
  'PAPUA NOVA GVINEJA': '🇵🇬',
  PARAGVAJ: '🇵🇾',
  PERU: '🇵🇪',
  POLjSKA: '🇵🇱',
  Portoriko: '🇵🇷',
  PORTUGALIJA: '🇵🇹',
  RUANDA: '🇷🇼',
  RUMUNIJA: '🇷🇴',
  'RUSKA FEDERACIJA': '🇷🇺',
  SAD: '🇺🇸',
  SAMOA: '🇼🇸',
  'SAN MARINO': '🇸🇲',
  'SAO TOME I PRINCIPE': '🇸🇹',
  'SAUDIJSKA ARABIJA': '🇸🇦',
  SEJŠELI: '🇸🇨',
  SENEGAL: '🇸🇳',
  'SENT KITS I NEVIS': '🇰🇳',
  'SENT VINSENT I GRENADINI': '🇻🇨',
  'SEVERNA MAKEDONIJA': '🇲🇰',
  'SIJERA LEONE': '🇸🇱',
  SINGAPUR: '🇸🇬',
  SIRIJA: '🇸🇾',
  SLOVAČKA: '🇸🇰',
  SLOVENIJA: '🇸🇮',
  'SOLOMONOVA OSTRVA': '🇸🇧',
  SOMALIJA: '🇸🇴',
  'SUDAN, REPUBLIKA': '🇸🇩',
  SURINAM: '🇸🇷',
  'SVETA LUCIJA': '🇱🇨',
  ŠPANIJA: '🇪🇸',
  ŠVAJCARSKA: '🇨🇭',
  ŠVEDSKA: '🇸🇪',
  TADžIKISTAN: '🇹🇯',
  TAJLAND: '🇹🇭',
  Tajvan: '🇹🇼',
  TANZANIJA: '🇹🇿',
  TOGO: '🇹🇬',
  TONGA: '🇹🇴',
  'TRINIDAD I TOBAGO': '🇹🇹',
  TUNIS: '🇹🇳',
  TURKMENISTAN: '🇹🇲',
  TURSKA: '🇹🇷',
  TUVALU: '🇹🇻',
  UGANDA: '🇺🇬',
  'UJEDINjENI ARAPSKI EMIRATI': '🇦🇪',
  UKRAJINA: '🇺🇦',
  URUGVAJ: '🇺🇾',
  VANUATU: '🇻🇺',
  'VELIKA BRITANIJA': '🇬🇧',
  VENECUELA: '🇻🇪',
  VIJETNAM: '🇻🇳',
  ZAMBIJA: '🇿🇲',
  ZIMBABVE: '🇿🇼',
};
