export const CLOSED_BORDER = 'CLOSED_BORDER';
export const NEGATIVE_TEST_REQUIRED = 'NEGATIVE_TEST_REQUIRED';
export const NO_TEST_REQUIRED = 'NO_TEST_REQUIRED';
export const OPEN_BORDER = 'OPEN_BORDER';
export const QUARANTINE_REQUIRED = 'QUARANTINE_REQUIRED';
export const SKIP_SENTENCE = 'SKIP_SENTENCE';
export const VACCINATION_CERTIFICATE = 'VACCINATION_CERTIFICATE';

export const SKIPPED_INTENTS = [OPEN_BORDER, SKIP_SENTENCE];

export const MODEL_LANGUAGE = 'sr';
